Feature/sections
awaazo/awaazo pull request #228
Opened 2023-12-16 01:05 UTC by Radwanbaba13

This pull request adds a series of commits that have fully implemented the sections feature on the frontend, including:

-  A component to view all sections, where you can manage existing sections such as deleting them.
- The ability to add sections, by adding a title and timestamps which are set with the help of a player bar, to facilitate the creation process for the user.  

Closes #176

2023-12-16 02:03 UTC, mathieutrudeau requested changes
Please add the cypress screenshots and vids to the gitignore.

2023-12-16 02:37 UTC, mathieutrudeau approved these changes
Looks good.

2023-12-16 02:50 UTC, jonathan-githubofficial requested changes
don't approve just yet

2023-12-17 06:43 UTC, jonathan-githubofficial requested changes

2023-12-17 06:43 UTC, jonathan-githubofficial commented on frontend/pages/NowPlaying/[EpisodeId].tsx
the section's useEffect should be handled in the "Sections" component. the section component in NowPlaying should only accept episode ID .

2023-12-17 06:43 UTC, jonathan-githubofficial commented on frontend/components/nowPlaying/Sections.tsx
the section's useEffect should be handled in the "Sections" component. the section component in NowPlaying should only accept episode ID .

2023-12-20 14:38 UTC, jonathan-githubofficial approved these changes

2023-12-20 15:35 UTC, merged