Feat/adjecent episode ids
awaazo/awaazo pull request #261
Opened 2023-12-27 06:53 UTC by mubashir494

Task Done
- Added Endpoint to return adjecent episode Ids 
- Configured the /EpisodeById to return the podcast Name
- Updated Unit tests

Closes : #251 and #232

2023-12-27 16:39 UTC, mathieutrudeau requested changes

2023-12-27 16:39 UTC, mathieutrudeau commented on Backend/Backend/Controllers/Responses/PodcastResponses.cs
> +public class EpisodeResponse2 : EpisodeResponse
I think adding the podcast name to the episode response class would make more sense.

2023-12-28 04:25 UTC, mathieutrudeau approved these changes
Good

2023-12-28 05:52 UTC, jonathan-githubofficial approved these changes
lg

2023-12-28 05:53 UTC, merged