Fix/player bar
awaazo/awaazo pull request #349
Opened 2024-01-26 21:51 UTC by Radwanbaba13

Closes https://github.com/awaazo/awaazo/issues/243
Closes https://github.com/awaazo/awaazo/issues/342

This PR introduces a series of fixes for:

Playerbar bugs (Such as like button not working)
Playerbar design
Playlist creation failing at submit due to endpoint request change
Queue, Create Playlists, and Add to Playlist modals not being general use
In addition, it introduced:

The Menu component to access different actions such share, queue management, adding episode to playlist...
The Chatbot frontend component to chat with an episode

2024-01-26 23:29 UTC, jonathan-githubofficial requested changes

2024-01-26 23:29 UTC, jonathan-githubofficial commented on frontend/pages/api/gpt-response.js
is this being implemented anywhere in the code. and if so , it must be in ts format and the right , folder for helpers.

2024-01-28 22:58 UTC, Radwanbaba13 commented on frontend/pages/api/gpt-response.js
This file has been deleted as it is not needed, the connection of chatBot component to the AI will be done through proper endpoint

2024-01-28 23:02 UTC, soni2261 commented
great work, hope it fixes the e2e tests💃

2024-01-29 01:14 UTC, mathieutrudeau approved these changes

2024-01-29 11:27 UTC, jonathan-githubofficial approved these changes

2024-01-29 12:27 UTC, merged