Fix/route protection
awaazo/awaazo pull request #406
Opened 2024-02-25 03:26 UTC by mubashir494

- Made all the Specified routes public

2024-02-25 14:45 UTC, mathieutrudeau requested changes
The service tests must also be updated to include tests for calling the service method with a null user.

2024-02-25 14:45 UTC, mathieutrudeau commented on Backend/Backend.Tests/PlaylistControllerTests.cs
> +        Assert.True(result != null);
The tests should be updated to reflect the changes in the controller. In this case we would expect a 200 ok response but getting a 500 error response would still make the test pass.

2024-02-25 22:38 UTC, mathieutrudeau requested changes

2024-02-25 22:38 UTC, mathieutrudeau commented on Backend/Backend.Tests/PlaylistControllerTests.cs
> +        Assert.IsType<OkObjectResult>(result);
To stay consistent in terms of naming tests, I think the tests should be renamed to something like GetUserPlaylists_ReturnsOkResult() and an extra assert should be added to check the value of the returned object.

2024-02-28 22:05 UTC, shadijiha approved these changes

2024-02-28 22:37 UTC, merged