Episode Transcript Implementation
awaazo/awaazo pull request #428
Opened 2024-03-07 00:22 UTC by soni2261

### **Features:**

**Display Transcript:**
- Allows a user to view a transcript on the NowPlaying page

**Edit Transcript:**
- Allows a user to edit a transcript on the Creator Hub

---

### **Implementation:**

**Transcript Component**
- Created a dedicated component to display the episode transcript

**Transcript Edit Modal**
- Created a dedicated component to edit the episode transcript

---

### **Risks Assessed:**

**Wrong text being written down**
- Indicating that the text being written is the owner's responsibility

**Performance issues on lower-end devices**
- Implemented a progressive enhancement strategy where the essential features are available to all users, and advanced features are selectively added based on the user's device capabilities.

**Browser Compatibility Issues:**
- Conducted cross-browser testing to address and resolve potential display issues with specific browsers.

**Potential layout shifts during toggle on different screen sizes**
- Optimizations have been implemented to minimize perceptible delays in synchronizing audio lines with the transcript, ensuring a smooth user experience.

---

**Closes #427**

2024-03-07 01:33 UTC, mathieutrudeau requested changes
These seem to cause trouble when running the backend tests. I will update this branch with the fix.

2024-03-07 01:54 UTC, soni2261 commented
okay yes thank you i tried to fix the migrations but it didn't work

2024-03-07 15:57 UTC, mathieutrudeau approved these changes

2024-03-10 05:31 UTC, jonathan-githubofficial approved these changes

2024-03-10 05:31 UTC, merged